language: ruby
rvm:
- 2.7.1

before_install:
- gem install bundler
- bundle

install:
- bundle install

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  skip_cleanup: true
  on:
    branch: master
