= Preferences
include::../../page-variables.txt[]
:page-permalink: /user-manual/english/misc/preferences

Use menu menu:File[Preferences...] (or menu:Antares[Preferences...] on macOS) to display the preferences window.

Select an entry of the tree in window's left part to display the preferences of a particular section. Once you've changed any of the preferences values, press button btn:[Apply] to apply your changes to Antares. If you press btn:[Close] without applying your changes, they wont become effective.

Some of the preferences can't be made effective without restarting the application. Antares will show a dialog if that's the case.

== General

Language:: The language in which texts of the user interface are displayed. Currently only English and German supported.

Log Level:: Determines the amount of log file output being produced. "Error" produces the least amount of log output, while "Trace" produces a lot of output and should normally only be used by developers.

Show tips for beginners:: If this option is enabled, Antares shows certain tooltips that should help beginners to familiarize with Antares' functionality. More experienced users can disable this option.

Show unexpected errors:: If this option is enabled, Antares shows an error dialog whenever an unexpected situation in the code arises. You can help supporting the project by following the description shown in the dialog to report this situation to the development team.

Data location:: Only relevant for the upcoming web version of Antares. Determines where Antares stores a user's projects and libraries.

Server URL:: Only relevant for the upcoming web version of Antares. Specifies the base URL of the Antares REST API.

== Network

Connection timeout [s]:: The duration in seconds after which Antares cancels trying to fetch a resource from a remote location (check for a new version, fetching configuration parameters etc.)

== Rendering

Main Font:: The font to be used for the UI elements. In the current version, circuit content still uses specific fonts which might differ from the UI font.

Sound effects:: If enabled, Antares plays sounds for certain actions, e.g. when a relay gets switched.

Theme:: The theme used for rendering the entire UI. The most important ones are "Winter", the standard light theme with white and blue coloring, and "Darcula", a dark theme.

Shadow:: If this option is enabled, circuit components like gates or switches are displayed with a drop shadow.

Shadow distance:: The number of pixels the shadow is placed apart from the origin component. Only effective if "Shadow" is enabled.

Fill basic components:: If enabled, basic components like gates or switches are filled with the theme's default color for filling content. Because sub circuit symbols are always filled, this option can help to visually distinguish between basic, built in components and subcircuit symbols. However, some basic components like LEDs are also always filled due to their nature.

== View

Show tree root handles:: If enabled, the root node of trees show a handle for expanding/collapsing the node.

Component tooltips:: If enabled, tooltips for circuit components are displayed when the mouse hovers over the component.

Tooltip delay (ms):: The time in milliseconds Antares waits before displaying a tooltip after the mouse stopped moving over a component.

=== Zoom / Pan

Pan method:: Determines how the user can pan the view (i.e. changing the region of the drawing displayed in the view).
- Press/hold middle mouse button
- ALT + press/hold left mouse button
- SPACE + press/hold middle mouse button

Pan step (mouse):: The amount of view displacement when panning with the mouse (drag with left mouse button pressed)

Zoom step:: The increment or decrement of the zoom factor when using menu:View[Zoom In] or menu:View[Zoom Out].

Zoom step (mousse wheel):: The increment or decrement of the zoom factor when zooming with the mouse wheel.

Default zoom factor:: The zoom factor applied when executing action menu:View[Zoom Normal].

Minimum zoom factor:: The minimum zoom factor.

Maximum zoom factor:: The maximum zoom factor.

Zoom factor in symbol editor:: The initial zoom factor used when switching to the symbol editor.

=== Navigation

Use animation when immerging into subcircuits:: If set, Antares plays an animation when you double click on a subcircuit symbol to immerge into it's inner circuit.

Switch mode using zoom factor:: If set, you can switch between the the circuit editor and the symbol editor by zooming out and zooming in with large factors.

== Editor

Grid distance:: The distance between grid snap points in model coordinate space. The default is 7. This value should normally not be changed, because the geometry of many components is aligned with this value, such as the distance between logic gate pins.

Grid dot step:: The number of "Grid distance" units between two grid dots (or grid lines, depending on "Grid rendering"). The default value is 2, which results in a distance of 14 between two grid dots if "Grid Distance" is 7.

Minimum grid dot distance:: The minimum distance between two grid dots (or grid lines, depending on "Grid rendering") in view coordinate space. Below this value, the grid is not drawn any more, which avoids drawing grid that are too dense and therefore useless.

Grid rendering:: The way the editor grid is drawn.
- **Lines**: A vertical and horizontal line is drawn at every grid location
- **Dots**: A dot is drawn at every grid location

Number of undo per snapshot:: The undo system uses snapshots (copies of the circuit) from which recorded actions are replayed when the user requests undoing or redoing them. This value determines how many actions are recorded before a new snapshot is created. Smaller values result in better performance, but more memory consumption, larger values may lead to worse performance. The default value is 10.

Selection box scope:: Determines how components are selected with the selection box. Pressing ALT while dragging the selection box temporarily switches between the two modes.
- **Completely contained**: Selects only components that are completely contained in the selection box.
- **Partially contained**: Selects also components that are only partially contained in the selection box.

Save history:: If enabled, Antares saves a copy of the previous version whenever a circuit is saved, which allows you to view the save history using menu:Popup[Show History..] and to restore old versions of a circuit.

Advanced wire layout (Experimental):: This mode for laying out wires tries to avoid overlapping segments of different wires.

Connect method:: The method used when creating new wires.
- **Auto-layout**: Press/hold the left mouse button on a pin or wire and drag the mouse onto a target pin or wire. Antares applies an orthogonal layout algorithm for the created wire.
- **Set points manually**: Click on a pin, click on intermediate points, and click on a target pin or wire. Antares does not apply any layout for the created wire.

== Simulation

Max. number of collected issues:: The maximum number of issues collected during a simulation run and displayed in the "Issues" tab.

Slow-down factor of simulation speed:: Determines how much the simulation speed is slowed down when dragging the simulation speed slider more to the left side. Larger values result in slower simulation speeds. The default is 4. The minimum value is 0.0001.

Allowed net contention duration (ns):: The time in nanoseconds during which net contention (i.e. conflicting signals on a net) are allowed without generating a simulation issue. The default is 20. +
Can be overwritten in projects and libraries.

Different color for non-zero multi-bit signal:: During simulation, wires and signal animation in multi-bit wires are painted in black for zero values. If set, non-zero values are painted in gray.

== Oscilloscope

Max. number of signal values:: The maximum number of signal values a row in the oscilloscope can store and display. If more signals arrive, the oldest ones are deleted.

Individual probe colors:: If set, the rows of an oscilloscope and their corresponding probe components are drawn in different, system defined colors.

Fill signal curve:: If set, signal curves in oscilloscope rows are filled with a fill color.

== Circuit

=== General

Symbol style:: The style in which symbols (primarily gates, but also others like resistors) are drawn. Choose between "ANSI/IEEE" (rounded symbols), "IEC" (rectangular symbols), and "Verbose" (rectangular with verbose label) style.

Style of generated symbols:: Determines whether and how Antares automatically generates symbols for your custom circuit.
- **None (deactivated)**: Antares doesn't generate symbols. You will have to draw them on your own using the symbol editor.
- **Narrow**: Antares generates narrow symbols that contain an abbreviation of the circuit name as label, as well as input and output pins.
- **Wide**: Antares generates wide symbols that contain the entire circuit name as label, as well as input and output pins.

Transistor with circle:: If set, transistors are drawn with a circle around the three pins.

Transistor pin names:: If set, transistor ports display a pin name, such as "G" for "Gate".

Display tri-state buffer as triangle:: If set, tri-state buffers are always drawn in the (American) triangle shape, independent of the current "Symbol style".

Adjust bit width to connected net:: If set, Antares attempts to adjust the bit width of a newly added component to the bit width of the net it gets connected to.

Calculate propagation delay upon save:: A circuit has a property "Propagation delay" which is used if the simulation mode isn't "Deep" and the circuit has an execution script. Antares has a utility function menu:File[Calculation propagation delay] to calculate this propagation delay. If the preference is set, the calculation is automatically done when the circuit is saved, and stored in the circuit's property (if not already set).

=== Digital

Default propagation delay (ns):: The default propagation delay (in nanoseconds) of logic gates (and some other components). Only applied for new components added to circuits. +
Can be overwritten in projects and libraries.

Undefined gate input behaviour:: Determines how Antares behaves if gates have undefined signals at their input pins during simulation. Can be overwritten in projects and libraries.
- **Read as 0**: Undefined signals are treated as if they were 0 (zero)
- **Read as 1**: Undefined signals are treated as if they were 1
- **Read as random value**: Undefined signal are randomly read as either 0 or 1.

Light color:: The default light color of light-emitting components like LEDs. Applied when such components are added to a circuit.

Signal representation:: The default kind of representing signal values in components like circuit inputs/outputs, or in signal flow animation. This default is applied to the corresponding circuit property when creating a new circuit, and can there be change to overwrite the system preference.

Signal notation:: Determines how signals are annotated to distinguish between different signal representations like "Binary" or "Hexadecimal".
- **Prefix**: Annotated with a prefix, e.g. "0x10" for hexadecimal 16.
- **Subscript**: Annotated with a subscript, e.g. "10&#x2081;&#x2086;"
- **Suffix**: Annotated with a suffix, e.g. "10h"
- **Suffix (Uppercase)**: Annotated with an uppercase suffix, e.g. "11H"

Tunnel symbol:: Determines the style in which link:{{site.basedir}}/user-manual/english/base-library/tunnel["Tunnel symbols"] are drawn.

Transistor symbol:: Determines the style in which link:{{site.basedir}}/user-manual/english/base-library/transistor["Transistor symbols"] are drawn.

Wide bus stroke:: If set, wires with a bit width larger than 1 are drawn with a wider stroke.

Switch propagation delay (ns):: The propagation delay in nanoseconds used for switch-like components like switch or DIP switch as default propagation delay. Default value is 1'000. +
Can be overwritten in projects and libraries.

Data path display in AND gates:: If set, the link:{{site.basedir}}/user-manual/english/base-library/and["Data Path"] feature for AND gates is generally enabled. Disable this option if you don't like that feature.

==== Expressions

Notation:: The default notation for boolean expression used when Antares generates them.

Omit AND for single character variable names:: If set, Antares omits "AND" operators when generating terms in boolean expressions whose variable names consist only of a single character, as in `AB or CD`.

Put AND terms in parenthesis:: If set, Antares puts AND terms in generated boolean expressions in parenthesis, as in `(AB) or (CD)` to explicitly denote operator precedence.

=== Analog

Current speed:: The speed of current flow animation in analog circuits. Supported values range from 1 (slow) to 10 (fast).

Simulation time step:: Determines how accurate the simulation of an analog circuit will be, especially when calculating capacitors or inductors. The lower the value, the more accurate the calculation, but the slower the simulation.

Draw LED halo:: If set, analog LEDs are drawn with a glowing halo during simulation.

=== Test cases

Check propagation delay consistency:: If set, executing test cases also checks whether the maximum of the measured propagation delays when executing circuit test cases is close to the configured propagation delay to be used for executing the circuit script (shallow simulation). If the propagation delays differ by more than 10%, a test fail is issued.