= Projects and Libraries
include::../../page-variables.txt[]
:page-permalink: /user-manual/english/projects-libraries/projects-libraries

== Overview

Projects and libraries are both ways in which several circuits can be combined and given a name. Internally they are very similar, and most of the actions you can perform as a user are available for both projects and libraries.

The difference between projects and libraries is that circuits from libraries can be reused in projects, whereas this is not possible with projects. Projects cannot be used in other projects. Libraries are therefore what their name says: a set of circuits that can be used in multiple projects.

== Libraries

Antares contains two libraries by default: The "Basic" library and the "Standard" library. Both libraries cannot be changed by you as a user. You can use their circuits in your own projects, you can open, execute and analyze their circuits, but you cannot change them, and you cannot add more circuits to these default libraries. This is because otherwise your changes would be overwritten when installing a new version of Antares.

The **Base library** contains only the basic components built-in into Antares, such as logic gates, LEDs, switches, etc. In the link:{{site.basedir}}/user-manual/english/base-library/base-library[Library Reference] you find a description of these base components. You can use the base library to create projects that build circuits "from scratch". You can also use the base library as a starting point to create your own libraries.

The **Standard Library** also contains all the basic built-in components of Antares. Additionally, it contains important, frequently used subcircuits such as flip-flops, registers and multiplexers that you can include into your own projects.

The choice of subcircuits available in the standard library was largely determined by the development of the example circuit "Microcomputer (Tanenbaum)", the circuit that has played a directing role in the design and development of Antares. In future versions of Antares it is likely that additional subcircuits will be added to the standard library.

However, an important feature of libraries is that you can create your own libraries that suit your own particular needs. Not only will you learn a lot about how Antares works, but you can also use the features link:{{site.basedir}}/user-manual/english/description/description["Descriptions and explanations"] to explain your library subcircuits. Especially if you are a teacher or an author, you should definitely consider developing your own library after you have gained some deeper experience with Antares.

In the chapter link:{{site.basedir}}/user-manual/english/projects-libraries/libraries[Libraries] you will learn how to work with libraries and how to create your own libraries.

== Projects

Projects combine circuits that you need for a specific application and that together fulfill a particular function. Projects can import an arbitrary number of libraries from which it can consume circuits. The example project "Microcomputer (Tanenbaum)" is based on the standard library and contains circuits like "CPU", "Address Decoder" and "ALU 16-Bit".

In the chapter link:{{site.basedir}}/user-manual/english/projects-libraries/projects[Projects] you will learn how to work with projects and create your own projects.

== Workbench

The link:{{site.basedir}}/user-manual/english/projects-libraries/workbench[Workbench] is the part of the Antares user interface that displays the open project and the libraries it is based on, and allows you to use its circuits and create new ones.

== Storage

When Antares is started for the first time, it creates a working directory named "Antares" and uses this directory to store your projects and your own libraries.

The location of this working directory depends on the operating system. On macOS, the directory is in the following location, where `{userName}' is your user name:

 /Users/{userName}/Library/Application Support/Antares

If you edit a single circuit, you must explicitly save your changes, i.e. you should regularly execute the menu:File[Save] action. As long as such changes are not saved, they can be undone using the undo system.

However, changes to the structure of projects and libraries are always saved automatically. For example, if you delete a directory in a project, this directory disappears from the workbench and the new project structure is immediately saved in the working directory of Antares. Since such actions cannot be undone, Antares will ask you for a confirmation before executing such actions.

NOTE: As of release 0.2, actions on projects and libraries are disabled if the main circuit contains unsaved changes. This is to avoid inconsistent states when undoing and redoing main circuit changes while project and library states have changed in the meantime.

== Workspace

As of release 1.5, Antares allows you to choose the directory where Antares stores your custom projects and libraries. This directory is called "Workspace". Use menu menu:File[Open Workspace...] to switch to another workspace. Antares remembers the workspace you've chosen in its application settings file and automatically opens that workspace the next time you start Antares.

[Note]
====
Note that the application settings, user preferences and log files are still stored in the application data directory, which you cannot chance.
====